#!/bin/bash

echo "*********************************************"
echo "*****   AUTO BUILD & PACKAGE SCRIPT     *****"
echo "*********************************************"

#OPTIONS : 
#	clean	 	- run make clean, remove stderr/stdout txt files and zips/files built by script, do not build kernel/zip
#	debug		- clean up, build kernel normally except redirect stderr/stdout to txt files, do not build flashable zip
#	noclean		- build kernel normally except do not run 'make clean' or do any clean up first
#	nocleandebug	- same as debug except do not run 'make clean' or do any clean up first
#	(none)		- clean up, build kernel then produce flashable zip of kernel



#GLOBAL OPTIONS
ARCH=arm
TOOLCHAIN=~/android/Kernel/toolchains/bin/arm-eabi-
BASE_DIR="$( cd "$( dirname "$0" )" && pwd )"
DEFCONFIG=speedy_defconfig
DEFCONFIG_DIR=./arch/arm/configs/
NUMJOBS=6
OPTIONS=-o2
ZIPFILES=zip_template
ZIPPREFIX="JB-Speedy"
DEBUGTXT_CONFIG=config_debug.txt
DEBUGTXT_BUILD=build_debug.txt

#Pull local version from defconfig and append to zip file name
while read line; do
  if [[ $line == *"CONFIG_LOCALVERSION="* ]]  
  	then  	
  		VERSION=(${line//=/ })
  		VERSION=${VERSION[1]}
  		VERSION=${VERSION:1:(${#VERSION}-2)} 
  fi  
done < $DEFCONFIG_DIR$DEFCONFIG
ZIPNAME=$ZIPPREFIX$VERSION".zip"

#function to perform clean up operations
function cleanIt {
	echo ""
	echo "ACTION: make clean -j$NUMJOBS"
	make clean -j$NUMJOBS ARCH=$ARCH CROSS_COMPILE=$TOOLCHAIN 
	echo ""
	echo "ACTION: remove zip if present..."
	[ -f $ZIPNAME ] && rm $ZIPNAME
	echo ""
	echo "ACTION: remove txt files if present..."
	[ -f $DEBUGTXT_CONFIG ] && rm $DEBUGTXT_CONFIG
	[ -f $DEBUGTXT_BUILD ] && rm $DEBUGTXT_BUILD
}

#function to perform build operations
function buildIt {	
	#if 'debug' or 'nocleandebug' then redirect stderr/stdout
	if ( [[ $1 -eq 0 && $1 == nocleandebug ]] || [[ $1 -eq 0 && $1 == debug ]] );
		then
			echo ""
			echo "ACTION: make $DEFCONFIG"
			make $DEFCONFIG &> $DEBUGTXT_CONFIG
			echo ""
			echo "ACTION:"
			echo "make -j$NUMJOBS $OPTIONS ARCH=$ARCH CROSS_COMPILE=$TOOLCHAIN"
			make -j$NUMJOBS $OPTIONS ARCH=$ARCH CROSS_COMPILE=$TOOLCHAIN &> $DEBUGTXT_BUILD 
	#othewise just perform normal build
		else			
			echo ""
			echo "ACTION: make $DEFCONFIG"
			make $DEFCONFIG 
			echo ""
			echo "ACTION:"
			echo "make -j$NUMJOBS $OPTIONS ARCH=$ARCH CROSS_COMPILE=$TOOLCHAIN"
			make -j$NUMJOBS $OPTIONS ARCH=$ARCH CROSS_COMPILE=$TOOLCHAIN 	
	fi			
}

#function to create flashable zip
function zipIt {
	echo ""
	echo "ACTION: create working directory..."
	rm -fr tmpdir
	mkdir tmpdir

	echo ""
	echo "ACTION: copy package template to working directory..."
	cp -a $ZIPFILES tmpdir/zipf
	mkdir tmpdir/zipf/system
	mkdir tmpdir/zipf/system/lib
	mkdir tmpdir/zipf/system/lib/modules

	echo ""
	echo "ACTION: copy kernel image over..."
	cp arch/arm/boot/zImage tmpdir/zipf/kernel

	echo ""
	echo "ACTION: copying all modules over..."
	for j in $(find . -name "*.ko"); do
	    cp "${j}" tmpdir/zipf/system/lib/modules/
	done

	echo ""
	echo "ACTION: creating CWM flashable zip..."

	cd tmpdir/zipf
	zip -r $ZIPNAME *
	cp -R $ZIPNAME $BASE_DIR
	cd ../../
	rm -fr tmpdir

	echo ""
	echo ""
	echo "ACTION: Zip $ZIPNAME built and placed in root dir..."

}

#Clean up if argument calls for it
if ( [[ $1 -eq 0 && $1 == noclean ]] || [[ $1 -eq 0 && $1 == nocleandebug ]] );
	then 		
		echo ""
		echo "skipping cleanup..."
	else
		echo $1
		echo ""
		echo "Beginning clean up..."
		cleanIt
		echo ""
		echo "Clean up complete..."		
fi

#If argument is 'clean' then don't perform build, otherwise build
if ( [[ $1 -eq 0 && $1 == clean ]] );
	then
		exit
	else
		echo ""
		echo "Beginning build process......"
		buildIt $1
		echo ""
		echo "Build finished......"
fi

#Create zip if argument calls for it
if ( [[ $1 -eq 0 && $1 == noclean ]] || [[ !"$1" ]] );
	then 		
		echo ""
		echo "Beginning packaging process......"
		if [ -e arch/arm/boot/zImage ];
			then
				zipIt
				echo ""
				echo "Packaging finished......"	
			else
				echo ""
				echo "Cannot create package, build must have failed!"
		fi	
fi







